version: '3'
services:
  nginx_front:
    image: nginx:stable
    ports:
      - "3000:80"
    depends_on:
      - web
    volumes:
      - ./nginx_front/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/web
    restart: always
    networks:
      - app_network

  web:
    build: ./web
    volumes:
      - ./web:/var/www/web
    networks:
      - app_network

  nginx_back:
    image: nginx:stable
    ports:
      - "9000:80"
    depends_on:
      - server
    volumes:
      - ./nginx_back/default.conf:/etc/nginx/conf.d/default.conf
      - ./server:/var/www/server
    restart: always
    networks:
      - app_network

  server:
    # build: ./server
    image: openjdk:11
    tty: true
    volumes:
      - ./server:/var/www/server
    working_dir: /var/www/server
    expose:
      - 9000
    command: sh gradlew bootRun
    networks:
      - app_network

networks:
  app_network:
