FROM openjdk:11
# COPY ./server/gradlew ./var/www/server/
# RUN ["./var/www/server/gradlew", "server:build"]

# FROM openjdk:11

WORKDIR /var/www/server

# COPY ./build/libs/server.jar .
# ENTRYPOINT ["java", "-jar", "server.jar"]
